---
abstract: 'DateTime base recurrences'
author:
  - 'Flavio S. Glock <fglock@pucrs.br>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150001'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DateTime-Event-Recurrence
no_index:
  directory:
    - t
    - inc
requires:
  DateTime: '0.27'
  DateTime::Set: '0.3600'
resources:
  repository: https://github.com/fglock/DateTime-Event-Recurrence.git
version: '0.18'
